#!/bin/bash
# Usage: setwp -h
# Author: Skiqqy
# This script allows the setting of a static wallpaper, or cycling through a set of wallpapers.

# Variables
set -B
t=600
args=( "$@" )

usage () {
cat << EOF
Usage: setwp [options] [file|dir]

h: Shows this message.
d: Use the pictures in the specified directory, cycle with time t (default 10 min).
t: set time t to a specific value.
z: Make feh zoom in on the wallpapers.
f: specify a single picture to use.
EOF
}

swp () {
	if [ -z $zoom ]
	then
		feh --bg-scale $1
	else
		feh --bg-fill $1
	fi
}

# cycle /path/to/dir
cycle () {
	d=${1%/}
	if [ $(echo "$t < 1" | bc) -eq 1 ]
	then
		echo "Invalid time used: t was '$t', now set to '600'"
		t=600
	fi
	for ((;;))
	do
		for file in $d/{*.png,*.jpg,*.jpeg}
		do
			swp $file
			sleep $t
			if [ ! $? -eq 0 ]
			then
				echo "An error occured in cycle, did you set time to a valid number?"
				exit 1
			fi
		done
	done
}

# Downloads and sets a wallpaper, provides an option to save permanently.
# Usage: download "$url"
download ()
{
	ftype=$(basename "$1" | cut -d\. -f 2)
	file=/tmp/"testwp.$ftype"
	curl -s "$1" > "$file"

	if ! swp "$file" > /dev/null 2>&1
	then
		echo "An error occured, is this a valid picture link?"
		exit $?
	fi

	read -rp "Save? Y/N: " input
	[[ ! "$input" =~ ^(y|Y)(es)?$ ]] && exit # Exit if we not saving

	read -rp "Name (Empty for random name): " name
	[ -z "$name" ] && name=$(tr -dc 0-9A-Za-z < /dev/random | head -c 15)
	read -rep "Path (Empty for curr dir): " save
	[ -z "$save" ] && save=.
	save=$(realpath "${save%/}")

	if [ -f "$save/$name.$ftype" ]
	then
		read -rp "This file already exist! Proceed? Y/N: " input
		[[ "$input" =~ ^(n|N)(o)?$ ]] && echo "Save aborted." && exit 0
	fi

	echo "Saving! $save/$name.$ftype"
	mv "$file" "$save/$name.$ftype"
	exit
}

main ()
{
	last=$((${#args[@]} - 1))
	[ "$last" -eq -1 ] && usage && exit 1
	file=${args["$last"]}
	zoom=

	while getopts "hd:t:zf:" opt
	do
		case $opt in
			h)
				usage
				exit 0
				;;
			t)
				t="$OPTARG"
				;;
			z)
				zoom=1
				;;
			f|d)
				file="$OPTARG"
				;;
			*)
				echo "Invalid arg"
				exit 1
				;;
		esac
	done

	[[ "$file" =~ ^http[s]?:// ]] && download "$file" # Check that it is a url

	[ -z "$file" ] && echo "Invalid file, see -h" && exit 1

	if [ -d "$file" ]
	then
		cycle "$file"
	elif [ -f "$file" ]
	then
		swp "$file"
	else
		echo "<ERROR> Please check -h"
		exit 1
	fi
}

main "$@"
