#!/bin/bash
# A simple way for me to quickly test wallpapers.

[ ! "$#" -eq 1 ] && exit 1
[[ ! "$1" =~ ^http[s]?:// ]] && exit 1 # Check that it is a url.
ftype=$(basename "$1" | cut -d\. -f 2)
file=/tmp/"testwp.$ftype"
curl -s "$1" > "$file"

if ! setwp "$file" > /dev/null 2>&1
then
	echo "An error occured, is this a valid picture link?"
	exit $?
fi

read -rp "Save? Y/N: " input
[[ ! "$input" =~ ^(y|Y)(es)?$ ]] && exit # Exit if we not saving

read -rp "Name (Empty for random name): " name
[ -z "$name" ] && name=$(tr -dc 0-9A-Za-z < /dev/random | head -c 15)
read -rep "Path (Empty for curr dir): " save
[ -z "$save" ] && save=.
save=$(realpath "${save%/}")

if [ -f "$save/$name.$ftype" ]
then
	read -rp "This file already exist! Proceed? Y/N: " input
	[[ "$input" =~ ^(n|N)(o)?$ ]] && echo "Save aborted." && exit 0
fi

echo "Saving! $save/$name.$ftype"
mv "$file" "$save/$name.$ftype"
